schema:
  - './packages/api/src/graphql/domains/*/schema.graphql'
  - './packages/app2/src/*/schema.graphql'
documents: './packages/app2/src/**/*.{ts,tsx}'
extensions:
  languageService:
    # Use eslint for linting instead of VScode GraphQL Plugin
    # Allows for more customization. E.g. exclude tests files
    enableValidation: false
