version: '3.8'

services:
  mongo-express:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/mongo?authSource=admin
    networks:
      - mongo-network
    ports:
      - 8081:8081

networks:
  mongo-network:
    external: true
