import { Changeset, SerializedChangeset } from '../changeset/changeset';
import {
  FilterEvents as RevisionRecordFilterEvents,
  RevisionRecords,
} from './revision-records';

export interface RevisionChangeset<T = Changeset> {
  revision: number;
  changeset: T;
}

export type SerializedRevisionChangeset = RevisionChangeset<SerializedChangeset>;

export type RevisionRecord<T = Changeset> = RevisionChangeset<T>;

export interface SelectionRange {
  start: number;
  end?: number;
}

/**
 * Record submitted by the client
 */
export interface SubmittedRevisionRecord<T = Changeset> extends RevisionRecord<T> {
  /**
   * A random ID generated by the client when record is created.
   * Used for preventing duplicate submissions.
   */
  userGeneratedId: string;
  /**
   * Selection before this record is composed
   */
  beforeSelection: SelectionRange;
  /**
   * Selection after this record is composed
   */
  afterSelection: SelectionRange;
}

/**
 * Record processed by the server.
 */
export interface ServerRevisionRecord<T = Changeset> extends SubmittedRevisionRecord<T> {
  creatorUserId: string;
}

export function isExistingRecordByUserGeneratedId<
  TRecord extends Pick<SubmittedRevisionRecord, 'userGeneratedId'>,
>(event: RevisionRecordFilterEvents<TRecord>['isExistingRecord']) {
  if (event.isExisting) return event;

  return {
    ...event,
    isExisting: event.newRecord.userGeneratedId === event.existingRecord.userGeneratedId,
  };
}

export function followRecordSelection<
  TRecord extends Pick<
    SubmittedRevisionRecord,
    'beforeSelection' | 'afterSelection' | 'changeset'
  >,
>(event: RevisionRecordFilterEvents<TRecord>['followRecord']) {
  const { existingRecord: record, newRecord: follow } = event;

  followSelection(record.changeset, follow.beforeSelection);
  followSelection(record.changeset, follow.afterSelection);

  return event;
}

function followSelection(changeset: Changeset, selection: SelectionRange) {
  selection.start = changeset.followIndex(selection.start);
  if (selection.end != null) {
    selection.end = changeset.followIndex(selection.end);
  }
}

export function addFiltersToRevisionRecords<TRecord extends ServerRevisionRecord>(
  revisionRecords: RevisionRecords<TRecord>
) {
  revisionRecords.filterBus.on('isExistingRecord', isExistingRecordByUserGeneratedId);
  revisionRecords.filterBus.on('followRecord', followRecordSelection);
}
