import { ObjectId } from 'mongodb';
import { RevisionChangeset } from '../../records/revision-changeset';
import { Changeset } from '../../changeset/changeset';
import { Record } from '../../records/revision-records';

export interface SelectionRange {
  start: number;
  end?: number;
}

export interface RevisionRecord<T = Changeset> extends Record<T> {
  creatorUserId: ObjectId;
  /**
   * A random ID generated by client when record is created.
   * Used for detecting and preventing duplicate submission.
   */
  userGeneratedId: string;
  beforeSelection: SelectionRange;
  afterSelection: SelectionRange;
}

export interface CollaborativeDocument<T = Changeset> {
  headDocument: RevisionChangeset<T>;
  tailDocument: RevisionChangeset<T>;
  records: RevisionRecord<T>[];
}

export function createInitialDocument(
  creatorUserId: ObjectId,
  initalText: string
): CollaborativeDocument {
  const changeset = Changeset.fromInsertion(initalText);
  return {
    headDocument: {
      revision: 0,
      changeset,
    },
    tailDocument: {
      revision: -1,
      changeset: Changeset.EMPTY,
    },
    records: [
      {
        creatorUserId,
        userGeneratedId: 'first',
        revision: 0,
        changeset,
        beforeSelection: {
          start: 0,
        },
        afterSelection: {
          start: initalText.length,
        },
      },
    ],
  };
}
