version: '3.8'

services:
  mongo:
    image: mongo:6
    command: ['--replSet', 'rs0', '--bind_ip_all', '--port', '27017']
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'127.0.0.1:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 3s
      timeout: 10s
      start_period: 0s
      start_interval: 1s
      retries: 5
    environment:
      MONGO_INITDB_DATABASE: mongo
    container_name: mongo
    networks:
      - mongo-network
      - sam-api-network
    ports:
      - 27017:27017

networks:
  mongo-network:
    name: mongo-network
  sam-api-network:
    name: sam-api-network
