name: CI up to ci:test

on:
  push:
    branches: ['ci']
  pull_request:
    branches: ['ci']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  APP_ORIGIN: http://localhost
  VITE_GRAPHQL_HTTP_URL: http://localhost:4010/graphql
  VITE_GRAPHQL_WS_URL: ws://localhost:4010/graphql
  DEBUG_FORMAT: json
  MOCK_MONGODB_URI: mongodb://localhost:27017/notesTest?replicaSet=rs0
  MOCK_DYNAMODB_ENDPOINT: http://localhost:8000
  MONGODB_TIER: enterprise
  VITE_MOCK_GOOGLE_AUTH: true
  TEST_MONGODB_URI: mongodb://localhost:27017/notesTest?replicaSet=rs0
  TEST_DYNAMODB_ENDPOINT: http://localhost:8000
  TEST_DOCKER_MONGODB_URI: mongodb://mongod:27017/notesTest?replicaSet=rs0&directConnection=true
  TEST_DOCKER_DYNAMODB_ENDPOINT: http://dynamodb-local:8000
  TEST_MONGODB_TIER: enterprise
  TEST_DEBUG_FORMAT: object
  # Eslint print time spent on a rule
  TIMING: 1

  NODE_VERSION: 22.x

jobs:
  build:
    name: GraphQL codegen, Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Clean install
        run: npm ci

      # Artifact packages/api/src/graphql/domains/*.generated.ts
      - name: Api GraphQL codegen
        run: npm run -w api graphql:gen

      # Artifact packages/app/src/__generated__/**
      # Artifact packages/api-dev-server/graphql-gen-server.log
      - name: App GraphQL codegen, Possible types from Api
        run: npm run -w app graphql:gen

      - name: Upload GraphQL gen server logs
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: graphql_gen_server_logs
          path: |
            packages/api-dev-server/graphql-gen-server.log
          retention-days: 2

      - name: Upload GraphQL codegen
        uses: actions/upload-artifact@v4
        with:
          name: graphql_gen
          # Common path ancestor ./packages/
          path: |
            packages/api/src/graphql/domains/*.generated.ts
            packages/app/src/__generated__/**
          retention-days: 2          

      # Artifact packages/api/out/**
      - name: Build api
        run: npm run -w api build

      # Artifact packages/app/out/**
      - name: Build app
        run: npm run -w app build

      # Artifact packages/api-dev-server/out/**
      - name: Build dev server for testing
        run: npm run -w dev-server build

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: build
          # Common path ancestor ./packages/
          path: |
            packages/api/out/**
            packages/app/out/**
            packages/api-dev-server/out/**
          retention-days: 2
  lint:
    name: Type check, eslint
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          [api, api-app-shared, dev-server, app, collab, infra, lambda-graphql, utils]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Download Graphql codegen artifacts
        uses: actions/download-artifact@v4
        with:
          name: graphql_gen
          path: packages

      - name: Clean install
        run: npm ci

      - name: Type check
        run: npm run -w ${{ matrix.package }} type-check

      - name: Eslint
        run: npm run -w ${{ matrix.package }} eslint
  test_unit:
    name: Unit tests
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [api, app, collab, infra, utils]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Download GraphQL codegen artifacts
        uses: actions/download-artifact@v4
        with:
          name: graphql_gen
          path: packages

      - name: Clean install
        run: npm ci

      - name: Run tests
        run: npm run -w ${{ matrix.package }} test:unit
  test_int:
    name: Integration tests
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [api, infra, lambda-graphql]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Download GraphQL codegen artifacts
        uses: actions/download-artifact@v4
        with:
          name: graphql_gen
          path: packages    

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: packages

      - name: Clean install
        run: npm ci

      - name: Initialize docker
        run: npm run docker:init

      - name: Start MongoDB container
        run: npm run mongodb:start

      - name: Start DynamoDB container
        run: npm run dynamodb:start

      - name: Run integration tests
        run: npm run -w ${{ matrix.package }} test:int
  test_comp:
    name: App component tests
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Download GraphQL codegen artifacts
        uses: actions/download-artifact@v4
        with:
          name: graphql_gen
          path: packages

      - name: Clean install
        run: npm ci

      - name: Run component tests
        run: npm run -w app test:comp
  test_e2e:
    name: End-to-end tests
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [api]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: packages

      - name: Clean install
        run: npm ci

      - name: Initialize docker
        run: npm run docker:init

      - name: Start MongoDB container
        run: npm run mongodb:start

      - name: Start DynamoDB container
        run: npm run dynamodb:start

      # Artifact packages/api-dev-server/dev-server.log
      - name: Run end-to-end tests
        run: npm run -w ${{matrix.package }} test:e2e

      - name: Upload dev server logs
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: dev_server_logs
          path: |
             packages/api-dev-server/dev-server.log
          retention-days: 2
