# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI up to ci:synth on main

on:
  push:
    branches: ['ci']
  pull_request:
    branches: ['ci']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  APP_ORIGIN: http://localhost
  VITE_GRAPHQL_HTTP_URL: http://localhost:4000/graphql
  VITE_GRAPHQL_WS_URL: ws://localhost:4000/graphql
  DEBUG_FORMAT: json
  MOCK_MONGODB_URI: mongodb://localhost:27017/notesDev?replicaSet=rs0
  MOCK_DYNAMODB_ENDPOINT: http://localhost:8000
  MONGODB_TIER: 'enterprise'
  VITE_MOCK_GOOGLE_AUTH: true
  # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
  NODE_VERSION: 22.x

jobs:
  test_e2e_tmp:
    name: End-to-end testing temporary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Clean install
        run: npm ci

      - name: Initialize docker
        run: npm run docker:init

      - name: Start MongoDB container
        run: npm run mongodb:start

      - name: Start DynamoDB container
        run: npm run dynamodb:start

      - run: npm run -w api graphql:gen
      - run: npm run -w dev-server build
      - run: ls -la packages/api-dev-server/out
      - run: DEBUG=*:ERROR,*:INFO NODE_ENV=test node packages/api-dev-server/out/server/index.mjs > dev-server.log 2>&1 &
      - run: sleep 10

      - uses: actions/upload-artifact@v4
        with:
          name: tmp_server_logs
          path: |
            dev-server.log
          retention-days: 1

      - run: npx wait-port localhost:4010 -t 2000
      - run: kill $(lsof -t -i:4010)
  # graphql_codegen:
  #   name: Generate GraphQL code
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Use Node.js ${{ env.NODE_VERSION }}
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: ${{ env.NODE_VERSION }}
  #         cache: 'npm'

  #     - name: Clean install
  #       run: npm ci

  #     # Artifact packages/api/src/graphql/domains/*.generated.ts
  #     - name: Api GraphQL codegen
  #       run: npm run -w api graphql:gen

  #     # Artifact packages/app/src/__generated__/**
  #     - name: App GraphQL codegen and extract possible types from Api
  #       run: npm run -w app graphql:gen

  #     - name: Upload GraphQL codegen artifacts
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: graphql_codegen
  #         # Common path ancestor ./packages/
  #         path: |
  #           packages/api/src/graphql/domains/*.generated.ts
  #           packages/app/src/__generated__/**
  #         retention-days: 2
  # lint:
  #   name: Type check, eslint
  #   needs: graphql_codegen
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       package:
  #         [api, api-app-shared, dev-server, app, collab, infra, lambda-graphql, utils]
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Use Node.js ${{ env.NODE_VERSION }}
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: ${{ env.NODE_VERSION }}
  #         cache: 'npm'

  #     - name: Download GraphQL codegen artifacts
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: graphql_codegen
  #         path: packages

  #     - name: Clean install
  #       run: npm ci

  #     - name: Type check
  #       run: npm run -w ${{ matrix.package }} type-check

  #     - name: Eslint
  #       run: npm run -w ${{ matrix.package }} eslint
  # build:
  #   name: Build
  #   needs: graphql_codegen
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Use Node.js ${{ env.NODE_VERSION }}
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: ${{ env.NODE_VERSION }}
  #         cache: 'npm'

  #     - name: Download GraphQL codegen artifacts
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: graphql_codegen
  #         path: packages

  #     - name: Clean install
  #       run: npm ci

  #     # Artifact packages/api/out/**
  #     - name: Build api
  #       run: npm run -w api build

  #     # Artifact packages/app/out/**
  #     - name: Build app
  #       run: npm run -w app build

  #     # Artifact packages/api-dev-server/out/**
  #     - name: Build dev server for testing
  #       run: npm run -w dev-server build

  #     - name: Upload GraphQL codegen artifacts
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: build
  #         # Common path ancestor ./packages/
  #         path: |
  #           packages/api/out/**
  #           packages/app/out/**
  #           packages/api-dev-server/out/**
  #         retention-days: 2
  # test_unit:
  #   name: Unit testing
  #   needs: graphql_codegen
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       package: [api, app, collab, infra, utils]
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Use Node.js ${{ env.NODE_VERSION }}
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: ${{ env.NODE_VERSION }}
  #         cache: 'npm'

  #     - name: Download GraphQL codegen artifacts
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: graphql_codegen
  #         path: packages

  #     - name: Clean install
  #       run: npm ci

  #     - name: Run tests
  #       run: npm run -w ${{ matrix.package }} test:unit
  # test_int:
  #   name: Integration testing
  #   needs: graphql_codegen
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       package: [api, infra, lambda-graphql]
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Use Node.js ${{ env.NODE_VERSION }}
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: ${{ env.NODE_VERSION }}
  #         cache: 'npm'

  #     - name: Download GraphQL codegen artifacts
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: graphql_codegen
  #         path: packages

  #     - name: Clean install
  #       run: npm ci

  #     - name: Initialize docker
  #       run: npm run docker:init

  #     - name: Start MongoDB container
  #       run: npm run mongodb:start

  #     - name: Start DynamoDB container
  #       run: npm run dynamodb:start

  #     - name: Run integration tests
  #       run: npm run -w ${{ matrix.package }} test:int
  # test_comp:
  # name: App component testing
  # needs: graphql_codegen
  # runs-on: ubuntu-latest
  # steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v4

  #   - name: Use Node.js ${{ env.NODE_VERSION }}
  #     uses: actions/setup-node@v4
  #     with:
  #       node-version: ${{ env.NODE_VERSION }}
  #       cache: 'npm'

  #   - name: Download GraphQL codegen artifacts
  #     uses: actions/download-artifact@v4
  #     with:
  #       name: graphql_codegen
  #       path: packages

  #   - name: Clean install
  #     run: npm ci

  #   - name: Run component tests
  #     run: npm run -w app test:comp
  # test_e2e:
  #   name: End-to-end testing
  #   needs: [graphql_codegen, build]
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       package: [api]
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4
  #     - name: Use Node.js ${{ env.NODE_VERSION }}
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: ${{ env.NODE_VERSION }}
  #         cache: 'npm'

  #     - name: Download GraphQL codegen artifacts
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: graphql_codegen
  #         path: packages

  #     - name: Download build artifacts
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: build
  #         path: packages

  #     - name: Clean install
  #       run: npm ci

  #     - name: Initialize docker
  #       run: npm run docker:init

  #     - name: Start MongoDB container
  #       run: npm run mongodb:start

  #     - name: Start DynamoDB container
  #       run: npm run dynamodb:start

  #     - name: Run end-to-end tests
  #       run: npm run -w ${{ matrix.package }} test:e2e
